version: '3.7'

networks:
  glade:

volumes:
  glade-db:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: glade
        uid: 1000
    volumes:
      - ./src:/var/www/html
    container_name: glade
    networks:
      - glade

  mysql:
    image: mysql:8.0
    container_name: glade-mysql
    restart: unless-stopped
    ports:
      - 4406:3306
    env_file:
      - ./src/.env
    volumes:
      - glade-db:/var/lib/mysql
    networks:
      - glade
    depends_on:
      - php

  phpmyadmin:
    depends_on:
        - mysql
    image: 'phpmyadmin/phpmyadmin'
    environment:
        PMA_PORT: 3306
        PMA_HOST: mysql
    ports:
        - 8022:80
    networks:
        - glade
  
  nginx:
    depends_on:
      - php
      - mysql
    image: nginx:1.17-alpine
    container_name: glade-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - glade
